# Generated by Django 5.1.1 on 2024-10-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0005_rename_quentite_livre_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
