# Generated by Django 5.1.1 on 2024-10-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0002_auteur_date_de_naissance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='auteur',
            new_name='auteur_id',
        ),
    ]
