# Generated by Django 5.1.1 on 2024-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0006_alter_livre_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
