citations = [
    "Le succès, c'est d'aller d'échec en échec sans perdre son enthousiasme. (Winston Churchill)",
    "La vie, c'est 10 % ce qui nous arrive et 90 % comment nous y réagissons. (Charles R. Swindoll)",
    "Soyez le changement que vous voulez voir dans le monde. (Mahatma Gandhi)",
    "Le seul moyen de faire du bon travail est d'aimer ce que vous faites. (Steve Jobs)",
    "Ne jugez pas chaque jour à la récolte que vous faites, mais aux graines que vous semez. (Robert Louis Stevenson)",
    "Dans vingt ans, vous serez plus déçu par les choses que vous n'avez pas faites que par celles que vous avez faites. (Mark Twain)",
    "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute. (Confucius)",
    "Votre temps est limité, ne le gâchez pas en vivant la vie de quelqu'un d'autre. (Steve Jobs)",
    "On ne voit bien qu'avec le cœur, l'essentiel est invisible pour les yeux. (Antoine de Saint-Exupéry)",
    "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. (Eleanor Roosevelt)",
    "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information. (Albert Einstein)",
    "La vraie sagesse consiste à savoir que l'on ne sait rien. (Socrate)",
    "Il n'y a pas de chemin vers le bonheur, le bonheur est le chemin. (Lao Tseu)",
    "La vie est un mystère qu'il faut vivre, et non un problème à résoudre. (Gandhi)",
    "Ce n'est pas la destination qui compte, c'est le voyage. (Ralph Waldo Emerson)",
    "La vie est ce qui se passe pendant que vous êtes occupé à faire d'autres plans. (John Lennon)",
    "Vivre, c'est la chose la plus rare du monde. La plupart des gens se contentent d'exister. (Oscar Wilde)",
    "Chaque homme est coupable de tout le bien qu'il n'a pas fait. (Voltaire)",
    "Le bonheur n'est pas dans la possession, mais dans le partage. (Pierre Rabhi)",
    "Un pessimiste voit la difficulté dans chaque opportunité, un optimiste voit l'opportunité dans chaque difficulté. (Winston Churchill)",
    "Ce que nous faisons dans la vie résonne dans l'éternité. (Gladiator)",
    "La meilleure façon de prédire l'avenir est de l'inventer. (Alan Kay)",
    "Vous devez être le changement que vous souhaitez voir dans le monde. (Mahatma Gandhi)",
    "Le voyage de mille lieues commence par un pas. (Lao Tseu)",
    "L'échec est simplement l'opportunité de recommencer, cette fois de manière plus intelligente. (Henry Ford)",
    "Faites ce que vous pouvez, avec ce que vous avez, où vous êtes. (Theodore Roosevelt)",
    "Tout ce dont vous avez besoin est déjà en vous. (Rainer Maria Rilke)",
    "Ne comptez pas les jours, faites que les jours comptent. (Muhammad Ali)",
    "Le seul vrai échec est celui dont on ne tire aucune leçon. (John C. Maxwell)",
    "Il ne faut pas attendre d’être heureux pour sourire, mais sourire pour être heureux. (Edward L. Kramer)",
    "Le bonheur est réel seulement lorsqu'il est partagé. (Into the Wild)",
    "La vie est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre. (Albert Einstein)",
    "La seule manière de faire un excellent travail est d’aimer ce que vous faites. (Steve Jobs)",
    "Les seuls moyens de faire un excellent travail sont de travailler dur et d’aimer ce que vous faites. (Steve Jobs)",
    "Un but sans plan n'est qu'un souhait. (Antoine de Saint-Exupéry)",
    "Rien n'est impossible, l'impossible prend juste un peu plus de temps. (Dan Brown)",
    "Le véritable signe de l'intelligence n'est pas la connaissance mais l'imagination. (Albert Einstein)",
    "Il n'est jamais trop tard pour être ce que vous auriez pu être. (George Eliot)",
    "Ne rêvez pas votre vie, vivez vos rêves. (Mark Twain)",
    "Les gens peuvent oublier ce que vous avez dit, mais ils n'oublieront jamais comment vous les avez fait sentir. (Maya Angelou)",
    "La seule chose qui se dresse entre vous et votre rêve est la volonté d'essayer et la croyance que c'est réellement possible. (Joel Brown)",
    "Ne laissez pas le bruit des opinions des autres étouffer votre voix intérieure. (Steve Jobs)",
    "L'esprit est tout. Ce que vous pensez, vous le devenez. (Buddha)",
    "Votre vie est votre message pour le monde. Assurez-vous qu'il est inspirant. (Lori Deschene)",
    "Si vous pouvez le rêver, vous pouvez le faire. (Walt Disney)",
    "La force ne vient pas des capacités physiques, mais d'une volonté indomptable. (Mahatma Gandhi)",
    "Tout ce que vous avez toujours voulu est de l'autre côté de la peur. (George Addair)",
    "N'attendez pas. Le temps ne sera jamais juste. (Napoleon Hill)",
    "Les difficultés ne doivent pas nous décourager, elles doivent nous inspirer. (Rosa Parks)",
    "L'art de la réussite consiste à savoir s'entourer des meilleurs. (John F. Kennedy)",
    "Le meilleur moyen de se réaliser est de se surpasser. (Eleanor Roosevelt)",
    "La qualité de votre vie est déterminée par la qualité de vos pensées. (Marcus Aurelius)",
    "La seule limite à notre réalisation de demain est nos doutes d'aujourd'hui. (Franklin D. Roosevelt)",
    "La créativité, c'est l'intelligence qui s'amuse. (Albert Einstein)",
    "La meilleure vengeance est un succès retentissant. (Frank Sinatra)",
    "Le seul moyen de faire du bon travail est d’aimer ce que vous faites. (Steve Jobs)",
    "La vie est un défi, relève-le ! (Mère Teresa)",
    "Les gens n'ont pas besoin d'être entendus, ils ont besoin d'être écoutés. (Jean-Pierre Lebrun)",
    "Tout est possible à celui qui rêve, ose, travaille et n'abandonne jamais. (Edgar Cayce)",
    "L'échec n'est pas l'opposé du succès, c'est une partie du succès. (Arianna Huffington)",
    "Les opportunités ne se produisent pas, vous les créez. (Chris Grosser)",
    "Ne laissez pas le passé voler votre présent. (Chérie Carter-Scott)",
    "La seule façon de faire un excellent travail est d’aimer ce que vous faites. (Steve Jobs)",
    "Rien n'est plus important que l'honnêteté envers soi-même. (Oscar Wilde)",
    "Tout ce qui ne nous tue pas nous rend plus fort. (Friedrich Nietzsche)",
    "L'esprit est tout. Ce que vous pensez, vous le devenez. (Buddha)",
    "Ce qui ne nous tue pas nous rend plus forts. (Friedrich Nietzsche)",
    "Un sourire coûte moins cher que l'électricité, mais donne autant de lumière. (Abbé Pierre)",
    "La vie est un défi, relève-le ! (Mère Teresa)",
    "Rien n'est permanent dans ce monde cruel. Pas même nos soucis. (Charlie Chaplin)",
    "Le véritable signe de l'intelligence n'est pas la connaissance mais l'imagination. (Albert Einstein)",
    "La vie est soit une aventure audacieuse, soit rien du tout. (Helen Keller)",
    "Le meilleur moyen de se réaliser est de se surpasser. (Eleanor Roosevelt)",
    "Le bonheur est un choix, pas une conséquence. (Ralph Marston)",
    "Ce que vous faites aujourd'hui peut améliorer tous vos lendemains. (Ralph Marston)",
    "Si vous n'essayez jamais, vous ne saurez jamais. (Michael Jordan)",
    "La vie est un défi, relève-le ! (Mère Teresa)",
    "Soyez vous-même; tout le monde est déjà pris. (Oscar Wilde)",
    "Ne laissez pas le bruit des opinions des autres étouffer votre voix intérieure. (Steve Jobs)",
    "Ce que vous faites aujourd'hui peut améliorer tous vos lendemains. (Ralph Marston)",
    "Vous ne trouvez pas le bonheur, vous le créez. (Unknown)",
    "Tout ce dont vous avez besoin est déjà en vous. (Rainer Maria Rilke)",
    "La créativité, c'est l'intelligence qui s'amuse. (Albert Einstein)",
    "Le seul moyen de faire un excellent travail est d’aimer ce que vous faites. (Steve Jobs)",
    "Le bonheur est réel seulement lorsqu'il est partagé. (Into the Wild)",
    "Si vous pouvez le rêver, vous pouvez le faire. (Walt Disney)",
    "Votre vie est votre message pour le monde. Assurez-vous qu'il est inspirant. (Lori Deschene)",
    "Les gens peuvent oublier ce que vous avez dit, mais ils n'oublieront jamais comment vous les avez fait sentir. (Maya Angelou)",
    "Ne rêvez pas votre vie, vivez vos rêves. (Mark Twain)",
    "Il n'est jamais trop tard pour être ce que vous auriez pu être. (George Eliot)",
    "Le véritable signe de l'intelligence n'est pas la connaissance mais l'imagination. (Albert Einstein)",
    "La meilleure façon de prédire l'avenir est de l'inventer. (Alan Kay)",
    "Ce que nous faisons dans la vie résonne dans l'éternité. (Gladiator)",
    "La seule vraie sagesse consiste à savoir que l'on ne sait rien. (Socrate)",
    "Rien n'est impossible, l'impossible prend juste un peu plus de temps. (Dan Brown)",
    "N'attendez pas. Le temps ne sera jamais juste. (Napoleon Hill)",
    "Les difficultés ne doivent pas nous décourager, elles doivent nous inspirer. (Rosa Parks)",
    "Un but sans plan n'est qu'un souhait. (Antoine de Saint-Exupéry)",
    "La vie est un mystère qu'il faut vivre, et non un problème à résoudre. (Gandhi)",
    "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute. (Confucius)",
    "La vie est ce qui se passe pendant que vous êtes occupé à faire d'autres plans. (John Lennon)",
    "Vivre, c'est la chose la plus rare du monde. La plupart des gens se contentent d'exister. (Oscar Wilde)",
    "Chaque homme est coupable de tout le bien qu'il n'a pas fait. (Voltaire)",
    "Le bonheur n'est pas dans la possession, mais dans le partage. (Pierre Rabhi)",
    "La seule chose qui se dresse entre vous et votre rêve est la volonté d'essayer et la croyance que c'est réellement possible. (Joel Brown)",
    "Ne laissez pas le bruit des opinions des autres étouffer votre voix intérieure. (Steve Jobs)",
    "L'esprit est tout. Ce que vous pensez, vous le devenez. (Buddha)",
    "Votre temps est limité, ne le gâchez pas en vivant la vie de quelqu'un d'autre. (Steve Jobs)",
    "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information. (Albert Einstein)",
    "Il n'y a pas de chemin vers le bonheur, le bonheur est le chemin. (Lao Tseu)",
    "L'avenir appartient à ceux qui croient en la beauté de leurs rêves. (Eleanor Roosevelt)",
    "Le voyage de mille lieues commence par un pas. (Lao Tseu)",
    "L'échec est simplement l'opportunité de recommencer, cette fois de manière plus intelligente. (Henry Ford)",
    "Faites ce que vous pouvez, avec ce que vous avez, où vous êtes. (Theodore Roosevelt)",
    "La seule vraie sagesse consiste à savoir que l'on ne sait rien. (Socrate)",
    "La créativité, c'est l'intelligence qui s'amuse. (Albert Einstein)",
    "Ne rêvez pas votre vie, vivez vos rêves. (Mark Twain)",
    "La vie est un défi, relève-le ! (Mère Teresa)",
    "Le bonheur est un choix, pas une conséquence. (Ralph Marston)",
    "Ce que vous faites aujourd'hui peut améliorer tous vos lendemains. (Ralph Marston)"
]
